Update deployment.yaml

diff --git a/Kubernetes/Components/CronManager/templates/deployment.yaml b/Kubernetes/Components/CronManager/templates/deployment.yaml
--- a/Kubernetes/Components/CronManager/templates/deployment.yaml
+++ b/Kubernetes/Components/CronManager/templates/deployment.yaml
@@ -36,45 +36,45 @@ spec:
               value: {{ .Values.images.commonservice.dsl.repo }}
             - name: DSL_PATH
               value: {{ .Values.images.commonservice.dsl.path }}
-        - name: init-copy-cron-files
-          image: "{{ .Values.images.cron.registry }}/{{ .Values.images.cron.repository }}:{{ .Values.images.cron.tag }}"
-          command: ["/bin/sh", "-c"]
-          args:
-            - |
-              pwd
-              cp -r ../DSL /shared-data
-              ls -la 
-          volumeMounts:
-            - name: shared-cron-volume
-              mountPath: /cron-data/    
-        - name: cron-dsl-symlink
-          image: busybox
-          securityContext:
-            runAsUser: 0     
-            runAsGroup: 0                    
-          command: ["/bin/sh", "-c"]
-          args:
-            - |
-              # Log directory permissions before attempting changes
-              echo "Initial permissions for /cron-data:"
-              ls -ld /cron-data
+        # - name: init-copy-cron-files
+        #   image: "{{ .Values.images.cron.registry }}/{{ .Values.images.cron.repository }}:{{ .Values.images.cron.tag }}"
+        #   command: ["/bin/sh", "-c"]
+        #   args:
+        #     - |
+        #       pwd
+        #       cp -r ../DSL /shared-data
+        #       ls -la 
+        #   volumeMounts:
+        #     - name: shared-cron-volume
+        #       mountPath: /cron-data/    
+        # - name: cron-dsl-symlink
+        #   image: busybox
+        #   securityContext:
+        #     runAsUser: 0     
+        #     runAsGroup: 0                    
+        #   command: ["/bin/sh", "-c"]
+        #   args:
+        #     - |
+        #       # Log directory permissions before attempting changes
+        #       echo "Initial permissions for /cron-data:"
+        #       ls -ld /cron-data
               
-              # Try to change ownership and permissions
-              echo "Attempting to change ownership and permissions..."
-              chown -R 1000:1000 /cron-data || echo "Failed to change ownership"
-              chmod -R 777 /cron-data/DSL || echo "Failed to change permissions"
+        #       # Try to change ownership and permissions
+        #       echo "Attempting to change ownership and permissions..."
+        #       chown -R 1000:1000 /cron-data || echo "Failed to change ownership"
+        #       chmod -R 777 /cron-data/DSL || echo "Failed to change permissions"
               
-              # Log directory permissions after changes
-              echo "Permissions for /cron-data after attempting change:"
-              ls -ld /cron-data/DSL
+        #       # Log directory permissions after changes
+        #       echo "Permissions for /cron-data after attempting change:"
+        #       ls -ld /cron-data/DSL
 
-              # Create symlink
-              ln -s /cron-data/DSL/* /DSL/
-          volumeMounts:
-            - name: cron-dsl
-              mountPath: /DSL/
-            - name: shared-cron-volume
-              mountPath: /cron-data/
+        #       # Create symlink
+        #       ln -s /cron-data/DSL/* /DSL/
+        #   volumeMounts:
+        #     - name: cron-dsl
+        #       mountPath: /DSL/
+        #     - name: shared-cron-volume
+        #       mountPath: /cron-data/
       containers:
       - name: "{{ .Values.release_name }}"
         image: "{{ .Values.images.scope.registry }}/{{ .Values.images.scope.repository }}:{{ .Values.images.scope.tag }}"
@@ -142,16 +142,16 @@ spec:
         - name: cronconst
           mountPath: /app/constants.ini
           subPath: constants.ini
-        - name: shared-cron-volume
-          mountPath: /cron-data/
-        - name: cron-dsl
-          mountPath: /DSL
+        # - name: shared-cron-volume
+        #   mountPath: /cron-data/
+        # - name: cron-dsl
+        #   mountPath: /DSL
       volumes:
       - name: cron-dsl
         emptyDir: {}
-      - name: shared-cron-volume
-        persistentVolumeClaim:
-          claimName: cron-pvc 
+      # - name: shared-cron-volume
+      #   persistentVolumeClaim:
+      #     claimName: cron-pvc 
       - name: trainbot-rasa-models
         persistentVolumeClaim:
           claimName: pvc-trainbot-models
